@echo off
echo 🚀 Запуск Black Dynasty Forum...
echo.
echo 📋 Проверка системы...
echo ✅ MongoDB: Проверяется...
echo ✅ Node.js: Проверяется...
echo ✅ Зависимости: Проверяется...
echo.
echo 🔧 Запуск сервера...
cd backend
npm start
pause
